-- Satellite Blog Network: micro blogs on separate domains
CREATE TABLE IF NOT EXISTS satellite_blogs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL,
  domain TEXT NOT NULL,
  name TEXT NOT NULL,
  topic TEXT NOT NULL,
  voice_profile JSONB NOT NULL DEFAULT '{}',
  parent_product TEXT NOT NULL,
  publishing_frequency TEXT DEFAULT '2-3/week',
  posts_generated INTEGER DEFAULT 0,
  backlinks_created INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'setup')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(account_id, domain)
);

CREATE INDEX IF NOT EXISTS idx_satellite_blogs_account ON satellite_blogs(account_id);
CREATE INDEX IF NOT EXISTS idx_satellite_blogs_product ON satellite_blogs(account_id, parent_product);

-- Satellite blog posts: individual articles published on satellite blogs
CREATE TABLE IF NOT EXISTS satellite_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL,
  satellite_blog_id UUID NOT NULL REFERENCES satellite_blogs(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  keyword TEXT,
  word_count INTEGER DEFAULT 0,
  has_product_link BOOLEAN DEFAULT FALSE,
  anchor_text TEXT,
  link_type TEXT CHECK (link_type IN ('branded', 'generic', 'contextual', NULL)),
  internal_links_count INTEGER DEFAULT 0,
  external_links_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'approved', 'published')),
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_satellite_posts_blog ON satellite_posts(satellite_blog_id);
CREATE INDEX IF NOT EXISTS idx_satellite_posts_account ON satellite_posts(account_id, created_at DESC);

-- Vertical Tools: free standalone micro-tools
CREATE TABLE IF NOT EXISTS vertical_tools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL,
  name TEXT NOT NULL,
  domain TEXT NOT NULL,
  parent_product TEXT NOT NULL,
  tool_type TEXT NOT NULL,
  description TEXT,
  target_keyword TEXT,
  visits INTEGER DEFAULT 0,
  cta_clicks INTEGER DEFAULT 0,
  conversions INTEGER DEFAULT 0,
  discount_codes_generated INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'setup')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(account_id, domain)
);

CREATE INDEX IF NOT EXISTS idx_vertical_tools_account ON vertical_tools(account_id);
CREATE INDEX IF NOT EXISTS idx_vertical_tools_product ON vertical_tools(account_id, parent_product);

-- Discount codes: generated by vertical tools for CTA conversions
CREATE TABLE IF NOT EXISTS discount_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL,
  code TEXT NOT NULL,
  tool_id UUID REFERENCES vertical_tools(id) ON DELETE SET NULL,
  product TEXT NOT NULL,
  discount_percent INTEGER DEFAULT 20,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'redeemed', 'expired')),
  redeemed_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  redeemed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  UNIQUE(account_id, code)
);

CREATE INDEX IF NOT EXISTS idx_discount_codes_tool ON discount_codes(tool_id);
CREATE INDEX IF NOT EXISTS idx_discount_codes_account ON discount_codes(account_id, status);
